### ISSUE TITLE
note attachment download counter

### ISSUE THREAD

**Issue by chunxiao1** [jlattimer/CRM-Note-Workflow-Utilities#1]
Hi Jason, 
    any chance this Utilities could support attachment download count? or any way we could develop an solution for that? thanks

**Comment by jlattimer** [comment]
Can you elaborate a bit more? The attachment count for a note would either be 0 or 1 because a note only has 1 attachment at most. You could determine if an attachment is present using the Check Attachment step.

**Comment by chunxiao1** [comment]
Hi I mean download count for each attachment, like the document has been download 5 times.

Thanks

发件人: Jason Lattimer [mailto:notifications@github.com]
发送时间: Friday, March 3, 2017 10:39 PM
收件人: jlattimer/CRM-Note-Workflow-Utilities <CRM-Note-Workflow-Utilities@noreply.github.com>
抄送: chunxiao1 <chunxiao.lin@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [jlattimer/CRM-Note-Workflow-Utilities] note attachment download counter (#1)


Can you elaborate a bit more? The attachment count for a note would either be 0 or 1 because a note only has 1 attachment at most. You could determine if an attachment is present using the Check Attachment step.

**Comment by jlattimer** [comment]
Probably not going to tackle this one since it would probably require a plug-in.
