### ISSUE TITLE
Copy Note step not working?

### ISSUE THREAD

**Issue by gresziu** [jlattimer/CRM-Note-Workflow-Utilities#2]
Hi, thanks for this utility, works very good so far!
But I've seen the step to copy a Note is not working? I attach some screenshots in case I'm missing anything. 
Dynamics 365 version, on-premises.
![w2](https://cloud.githubusercontent.com/assets/10895491/25492019/a5fc9130-2b69-11e7-88d4-8261ebb74f28.PNG)
![w1](https://cloud.githubusercontent.com/assets/10895491/25492020/a5fcbc64-2b69-11e7-9ef2-3886f669d5a0.PNG)

**Comment by jlattimer** [comment]
If you look at the workflow history, does it show the steps being executed?

**Comment by d4hines** [comment]
Hi Jason, 
I'd like to thank you for all the work on CRM developer tools. It's made my life so much easier!
I think I might be having the same issue as @gresziu , but perhaps we're just both misinterpreting the what's supposed to happen.

We created a workflow that runs on an annotation directly. The parameters were.
Note To Copy: {Note(Note)}
Record Dynamic Url: {RecordUrl(Dynamic)(Regarding(Person)} (which is just contact)
Copy Attachment: True (though in our case it didn't have an attachment)

We ran the workflow, and the history shows it as running successfully, but no note was created. Sure enough when we had it email us the output, the workflow is returning "Was Note Copied" as false. 

Any ideas? 

Screen shots below, though I'm not sure if they'll help. 
![image](https://user-images.githubusercontent.com/25231383/35348296-a5755c0c-0105-11e8-95ef-1cbd3c1c34dd.png)

**Comment by jlattimer** [comment]
Have you looked at things like security? Maybe try running as a system admin to see if that changes things?

**Comment by vernetmatias** [comment]
Hello Jason,
I want to reference "Note To Copy" with Note of a custom entity and I cant find the reference. Why is that? I uploaded an image here for you to check it.

![image](https://user-images.githubusercontent.com/36961292/36851339-c380b3be-1d47-11e8-9777-d0a6da918c6c.png)

Any solution?
Regards,
Matias

**Comment by vernetmatias** [comment]
Hi Jason,
Matias again, the requirement Im trying to do is that when the user creates a new note in the custom entity called "Formulario Folio" with an attachment it has to create a new Case with this attachement. How can I reference the attachment?

**Comment by jlattimer** [comment]
@vernetmatias The entity the workflow is executing against has to be Note. You won't be able to get a reference to it from the custom entity. What you could probably do is execute on Note and then 1st step add a check condition to see if the Regarding (Custom Entity) contains data. If it contains data it is related to your custom entity and then you can use the copy step
