### ISSUE TITLE
Move Note Setup

### ISSUE THREAD

**Issue by kjb1030** [jlattimer/CRM-Note-Workflow-Utilities#3]
Hi,

I am super excited about using this tool but I'm having some challenges with the setup. I created a WF on the Note entity and I want to copy notes from contacts to a related Case/Incident. Here are my screen shots of WF and error.

![image](https://user-images.githubusercontent.com/19617821/27151871-f3fa76b0-5119-11e7-9b80-0312c62495fe.png)

![image](https://user-images.githubusercontent.com/19617821/27151919-1beaddc2-511a-11e7-9d50-3a765024a7a4.png)

![image](https://user-images.githubusercontent.com/19617821/27151970-51addad6-511a-11e7-9fee-213d8a643076.png)

**Comment by jlattimer** [comment]
If the Note is attached to a Contact - the Note's Regarding Incident isn't going to be populated since it's related to the Contact - which is why the error is saying the url is empty. In the workflow you'd need another way of providing the Case record url.

**Comment by hnno82** [comment]
Dear jlattimer
thank your for your post but i got same error and i cant find another way to get the record url
regards
