### ISSUE TITLE
New Feature.

### ISSUE THREAD

**Issue by CnytSntrk** [jlattimer/CRM-Note-Workflow-Utilities#4]
Hi,
First, thank you for this great work.
I need a custom workflow that sends an email when the note is created on task.
To send an email to Task regarding Case owner.

But I'm newbie and couldn't do this.
Any help will be grateful thanks.

Note added on Task -> Send Email to Email's Regarding Task owner and Task's regarding Case owner.
Im using Dynamics Crm 365 online enviroment.

**Comment by jlattimer** [comment]
Nothing I've written will help with this I'm afraid. I don't think you can do this as you are traversing too many levels of relationships.
