### ISSUE TITLE
Issue (.url and operators)

### ISSUE THREAD

**Issue by magnusjeppesen** [jlattimer/CRM-Note-Workflow-Utilities#5]
Hi
Really like your tool, but I think I found a glitch.

On CRM 365 the tool doesn't seem to delete .url files. I've tested with all kinds of files, which all get delete, but it's not targeted against .url files.
I've both tried to not specify anything in the "Limit to extensions" and to specify "url"

Also it looks like the "<=" and ">=" operator labels are wrong. Since if nothing is defined it looks like it default to only delete files ">= 2,147,483,647" and "<= 0" which don't make much sense to me, unless I'm mistaken :)
See screenshot: https://imgur.com/a/wDESY

We are running v. 2.0.0.2 with the function "Delete attachment"

Kind regards.

**Comment by jlattimer** [comment]
Was able to delete a .url file when I tried.

![image](https://user-images.githubusercontent.com/1769982/37631786-2b0d21fa-2bb9-11e8-8a6f-511418af6d97.png)

![image](https://user-images.githubusercontent.com/1769982/37631797-38d93b7a-2bb9-11e8-8193-028a3debe595.png)
